"""Adiciona status ao modelo Evento

Revision ID: 79530fe3149d
Revises: da2470f52849
Create Date: 2025-10-15 22:22:02.133389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79530fe3149d'
down_revision = 'da2470f52849'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("event", schema=None) as batch_op:
        batch_op.add_column(sa.Column("status", sa.SmallInteger(), nullable=True))
    op.execute("UPDATE event SET status = 2")
    with op.batch_alter_table("event", schema=None) as batch_op:
        batch_op.alter_column("status", nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
