"""Replace abstract with file_path in Submission (HU05)

Revision ID: e4a3adbd57db
Revises: b4a98b1a2c3d
Create Date: 2025-10-24 21:35:51.684027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4a3adbd57db'
down_revision = 'b4a98b1a2c3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_path', sa.String(length=255), nullable=False))
        batch_op.drop_column('abstract')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('abstract', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.drop_column('file_path')

    # ### end Alembic commands ###
