"""Adicionar data de inicio e fim do periodo de inscricao dos Eventos

Revision ID: eea580de11f0
Revises: 79530fe3149d
Create Date: 2025-10-15 22:51:47.853398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eea580de11f0'
down_revision = '79530fe3149d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    import datetime
    now = datetime.datetime.now()
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('inscription_start_date', sa.DateTime(), nullable=False, server_default=sa.text(f"'{now.strftime('%Y-%m-%d %H:%M:%S')}'")))
        batch_op.add_column(sa.Column('inscription_end_date', sa.DateTime(), nullable=False, server_default=sa.text(f"'{now.strftime('%Y-%m-%d %H:%M:%S')}'")))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('inscription_end_date')
        batch_op.drop_column('inscription_start_date')

    # ### end Alembic commands ###
