"""add curso_id and turma_id to user table

Revision ID: 21c7f56a3abb
Revises: d60bc202fb1a
Create Date: 2025-10-26 03:26:08.317977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21c7f56a3abb'
down_revision = 'd60bc202fb1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faculdade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('curso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('duration_years', sa.Integer(), nullable=True),
    sa.Column('faculdade_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['faculdade_id'], ['faculdade.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('turma',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('academic_year', sa.String(length=10), nullable=True),
    sa.Column('semester', sa.SmallInteger(), nullable=True),
    sa.Column('curso_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['curso_id'], ['curso.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('curso_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('faculdade_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'faculdade', ['faculdade_id'], ['id'])
        batch_op.create_foreign_key(None, 'curso', ['curso_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('curso_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('turma_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'turma', ['turma_id'], ['id'])
        batch_op.create_foreign_key(None, 'curso', ['curso_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('turma_id')
        batch_op.drop_column('curso_id')

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('faculdade_id')
        batch_op.drop_column('curso_id')

    op.drop_table('turma')
    op.drop_table('curso')
    op.drop_table('faculdade')
    # ### end Alembic commands ###
