"""Add ActivityAttendance and check-in fields

Revision ID: 5a0896615918
Revises: c68106ac3a14
Create Date: 2025-10-26 21:00:57.111580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a0896615918'
down_revision = 'c68106ac3a14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_attendance',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('check_in_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'activity_id')
    )
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('check_in_open', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('check_in_code', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.drop_column('check_in_code')
        batch_op.drop_column('check_in_open')

    op.drop_table('activity_attendance')
    # ### end Alembic commands ###
