"""Add workload to Event model

Revision ID: 63a00afe6982
Revises: e4a3adbd57db
Create Date: 2025-10-25 08:16:07.880360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63a00afe6982'
down_revision = 'e4a3adbd57db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('workload', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('workload')

    # ### end Alembic commands ###
