"""Add allow_public_profile to User model

Revision ID: 83aa6ddb05ec
Revises: 63a00afe6982
Create Date: 2025-10-26 00:40:23.518207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83aa6ddb05ec'
down_revision = '63a00afe6982'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('allow_public_profile', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('allow_public_profile')

    # ### end Alembic commands ###
