"""Make allow_public_profile not null

Revision ID: 95c64f7943d4
Revises: 83aa6ddb05ec
Create Date: 2025-10-26 00:41:23.329210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95c64f7943d4'
down_revision = '83aa6ddb05ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('allow_public_profile',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('allow_public_profile',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###
