"""Add submission dates to event (HU05)

Revision ID: b4a98b1a2c3d
Revises: ajuste_default_datas_inscricao
Create Date: 2025-10-15 23:10:00.000000

"""
from alembic import op
import sqlalchemy as sa
from datetime import datetime, timezone

# revision identifiers, used by Alembic.
revision = 'b4a98b1a2c3d'
down_revision = 'ajuste_default_datas_inscricao'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Usaremos nullable=True para não quebrar eventos existentes.
    # Em uma implementação nova, definiríamos server_default.
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('submission_start_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('submission_end_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('submission_end_date')
        batch_op.drop_column('submission_start_date')

    # ### end Alembic commands ###